language: ruby
rvm:
  - 1.9.3
before_script:
  - psql -c 'create database devinsantos_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - RAILS_ENV=test bundle exec rspec spec