language: ruby
rvm:
  - 2.2.0
before_script:
  - cp config/database.example.yml config/database.yml
  - psql -c 'create database devinsantos_test;' -U postgres
script:
  - bundle exec rake --trace db:test:prepare
  - RAILS_ENV=test bundle exec rspec spec
