development:
  adapter: postgresql
  encoding: unicode
  database: devinsantos_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: devinsantos_test
  pool: 5
  username: postgres
  password:
  min_messages: WARNING

production:
  adapter: postgresql
  encoding: unicode
  database: devinsantos_production
  pool: 5
  username: postgres
  password:
