development:
  adapter: postgresql
  encoding: unicode
  database: devinsantos_development
  pool: 5
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: devinsantos_test
  pool: 5
  username: postgres
  password: postgres
  min_messages: WARNING
  host: localhost
